### PR TITLE
Create LICENSE

### LINKED ISSUE #7: Add MIT license.

### PR DESCRIPTION
**Pull request by skywalkerluc**
## Description
MIT License added

## Motivation and context
closes #7 

## What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes. (N/A)
- [x] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Comment by camigomez35** [comment]
Hi @skywalkerluc, this PR is related to the Issue #7, could you please assign that issue to yourself? 👍

**Comment by skywalkerluc** [comment]
Hi @camigomez35, I've never assigned an issue to myself before, but after researching I noticed I've got be considered a contributor or owner to do it. Can you help me?

**Comment by camigomez35** [comment]
Sure, please add a comment asking to be assign to that issue.

**Comment by skywalkerluc** [comment]
Oh, ok. Done!

**Comment by camigomez35** [comment]
Thanks @skywalkerluc!!

**Pull request merged**
